version: '3.8'

networks:
  app-network:

volumes:
  app-data:

services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: tv-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:

  db:
    container_name: tv-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'abdo'
      MYSQL_PASSWORD: 'power10v'
      MYSQL_ROOT_PASSWORD: 'D0tPAJqubDOJzGh'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "30000:3306"
    networks:
      app-network:

  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: tv-backend
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:
    depends_on:
      - db
