version: '3.8'

networks:
  test-app-network:

services:
  db:
    container_name: test-tv-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'abdo'
      MYSQL_PASSWORD: 'power10v'
      MYSQL_ROOT_PASSWORD: 'D0tPAJqubDOJzGh'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "30000:3306"
    networks:
      test-app-network:

  backend:
    restart: always
    build:
      context: ./
      dockerfile: .docker/dockerfile.test
    container_name: test-tv-backend
    env_file:
      - test.env
    volumes:
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      test-app-network:
    depends_on:
      - db