networks:
  app-network:

volumes:
  tv-db:
  tv-storage:


services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: tv-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT}:80"
    env_file:
      - prod.env
    volumes:
      - tv-storage:/var/www/public/avatars
      - tv-storage:/var/www/public/ethumbnails
      - tv-storage:/var/www/public/thumbnails
      - tv-storage:/var/www/storage/app/videos
      - tv-storage:/var/www/public/posters
      - ./public:/var/www/public
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:
    depends_on:
      - backend

  db:
    container_name: tv-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "30000:3306"
    networks:
      app-network:
    volumes:
      - tv-db:/var/lib/mysql

  backend:
    restart: always
    build:
      context: ./
      dockerfile: .docker/dockerfile
    container_name: tv-backend
    env_file:
      - prod.env
    volumes:
      - tv-storage:/var/www/public/avatars
      - tv-storage:/var/www/public/ethumbnails
      - tv-storage:/var/www/public/thumbnails
      - tv-storage:/var/www/public/posters
      - tv-storage:/var/www/storage/app/videos
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:
    depends_on:
      - db
